name: Deploy Project
on:  push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        # Aqui eu não precisava estar fazendo setup do node js, pois ele já vem configurado
        # no ubuntu. Estou fazendo apenas para treinar.
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        # Aqui eu não precisava estar fazendo setup do node js, pois ele já vem configurado
        # no ubuntu. Estou fazendo apenas para treinar.
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."